# NVIDIA CUDA Docker Compose (Explicit)
# For systems with NVIDIA GPUs when you want to force CUDA
# Requires: nvidia-container-toolkit
#
# Quick start:
#   docker compose -f docker-compose.cuda-explicit.yml up

services:
  claracore:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ollama-style
    image: claracore:universal
    container_name: claracore-cuda
    ports:
      - "5800:5800"
    volumes:
      - ./models:/models
      - ./config:/app/config
      - ./downloads:/app/downloads
      - ./binaries:/app/binaries
    environment:
      # Force CUDA backend
      - CLARACORE_BACKEND=cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - GIN_MODE=release
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
