services:
  claracore:
    build:
      context: ..
      dockerfile: docker/Dockerfile.universal
    image: claracore:universal
    container_name: claracore
    ports:
      - "5801:5801"
    volumes:
      # Mount your models folder here
      - ./models:/models
      # Persist config and downloads (as directories, not files)
      - ./config:/app/config
      - ./downloads:/app/downloads
      - ./binaries:/app/binaries
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # GPU support - works automatically if available
    # NVIDIA GPUs: Requires nvidia-docker runtime
    # AMD/Intel: Uses Vulkan (no special setup needed on Linux)
    # CPU-only: Falls back automatically
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    # Let ClaraCore auto-detect the best backend (CUDA > Vulkan > CPU)
    command: ["--listen", ":5801", "--models-folder", "/models", "--config", "/app/config/config.yaml"]
